// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace HotelFinder.Entities
{
    public partial class Hotels
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    }
}